### ISSUE TITLE
about evaluation results

### ISSUE THREAD

**Issue by JNash123** [eeskimez/emotalkingface#10]
Can u tell me how can I get the results of SSIM and PSNR

**Comment by yzyouzhang** [comment]
```
from skimage.metrics import structural_similarity as ssim
from cv2 import PSNR
```

**Comment by JNash123** [comment]
> ```
> from skimage.metrics import structural_similarity as ssim
> from cv2 import PSNR
> ```

I appreciate it，the inputs are image, noise, audio and emotion, and the output is video, then we calculate the PSNR and SSIM between the generated video frames and the ground-truth video frames. 
If the person of the generated video is the same with ground-truth video, how can I extract the face image in the ground-truth video , cuz i need to use it as the input.
