### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by jinholeetopology** [eeskimez/emotalkingface#8]
Hi. I have the following error when I used sample image img01.png and speech file speech01.wav.

python generate.py -im ./data/image_samples/img01.png -is ./data/speech_samples/speech01.wav -m ./model/ -o ./results/

result message : Image file is not valid...

Could you guess what I miss?

**Comment by eeskimez** [comment]
Hi,

Sounds like a  cv2.imread() error. Can you check and compare your OpenCV version? You can find the package versions we used in the "requirements.txt" file.

Thanks,
Emre

**Comment by JNash123** [comment]
> Hi,
> 
> Sounds like a cv2.imread() error. Can you check and compare your OpenCV version? You can find the package versions we used in the "requirements.txt" file.
> 
> Thanks, Emre

opencv-python==4.1.1.26, the version is the same with yours, i got the same error, Image file is not valid.
